name: handbook
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.*
  - pip
  - statsmodels
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - retrying
  - humanize
  - psutil
  - sphinx=2.4.4
  - pip:
    - xgboost
    - plotnine
    - chart-studio
    - quantecon  
    - jupyter-book>=0.7.0b
