# Book settings
title: Unboxing Machine Learning
author: Ritesh Agrawal
email: ragrawal@gmail.com
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex


# Navigate to https://analytics.google.com, add a new property for your jupyter book and copy the tracking id here.
google_analytics:
  mytrackingcode: UA-1286028-10

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)


#######################################################################################
# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  navbar_footer_text        : 'Powered by <a href="https://jupyterbook.org">Jupyter Book</a>'  # Will be displayed underneath the left navbar.
  google_analytics_id       : "UA-1286028-10"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
